CASE WHEN
LAG(PU_MIN("EKPO", "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 1) IS NULL 
OR (DAYS_BETWEEN(LAG(PU_MIN(EKPO, "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 1), "EKKO"."BEDAT") > 30
OR LAG("EKKO"."EBELN" , ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."TS_BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 1) =  "EKKO"."EBELN")
THEN '0'
ELSE 
shema.EKPO , ff._CEL_P2P_ACTIVITIES ,ff.EKKO
    CASE WHEN
    LAG(PU_MIN("EKPO", "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."TS_BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 2) IS NULL
    OR (DAYS_BETWEEN(LAG(PU_MIN(EKPO, "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 2), "EKKO"."BEDAT") > 30
    OR LAG("EKKO"."EBELN" , ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 2) =  "EKKO"."EBELN")
    THEN '1'
    ELSE
        CASE WHEN
        LAG(PU_MIN("EKPO", "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 3) IS NULL
        OR (DAYS_BETWEEN(LAG(PU_MIN(EKPO, "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 3), "EKKO"."BEDAT") > 30
        OR LAG("EKKO"."EBELN" , ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."TS_BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 3) =  "EKKO"."EBELN")
        THEN '2'
        ELSE
            CASE WHEN    
            LAG(PU_MIN("EKPO", "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 4) IS NULL
            OR (DAYS_BETWEEN(LAG(PU_MIN(EKPO, "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 4), "EKKO"."BEDAT") > 30
            OR LAG("EKKO"."EBELN" , ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 4) =  "EKKO"."EBELN")
            THEN '3'
            ELSE
                CASE WHEN  
                LAG(PU_MIN("EKPO", "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 5) IS NULL
                OR (DAYS_BETWEEN(LAG(PU_MIN(EKPO, "_CEL_P2P_ACTIVITIES"."EVENTTIME"), ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 5), "EKKO"."BEDAT") > 30
                OR LAG("EKKO"."EBELN" , ORDER BY("EKKO"."LIFNR", "EKPO"."EMATN", "EKKO"."TS_BEDAT"), PARTITION BY ("EKKO"."LIFNR", "EKPO"."EMATN"), 5) =  "EKKO"."EBELN")
                THEN '4'
                ELSE
                '5 or more'
            END
        END
    END
END
END